### ISSUE TITLE
200216 Object-Oriented Conference 1/3

### ISSUE THREAD

**Issue by stakiran** [stakiran/note#1]
聴講メモ

- https://github.com/stakiran/note/issues/2 ランチタイム 13:40 まで
- https://github.com/stakiran/note/issues/3 

## 全般
- [（本募集）Object-Oriented Conference - connpass](https://ooc.connpass.com/event/157193/)
- [交通アクセス・キャンパスマップ | お茶の水女子大学](http://www.ocha.ac.jp/access/ochacampusmap.html)
- [2020/カンファレンス催行基準及び注意喚起 - esa-pages.io](https://esa-pages.io/p/sharing/13679/posts/40/39ec737b3a3446310825.html)
    - 中止連絡は前日（2月15日）正午か当日9時
- [タイムテーブル | Object-Oriented Conference #ooc_2020 - fortee.jp](https://fortee.jp/object-oriented-conference-2020/timetable)
- [#ooc_2020 -from:@oocon_2020 - Twitter検索 / Twitter](https://twitter.com/search?q=%23ooc_2020%20-from%3A%40oocon_2020&src=typed_query&f=live)
- [from:@oocon_2020 - Twitter検索 / Twitter](https://twitter.com/search?q=from%3A%40oocon_2020&f=live)

## メモ方法
- コメントとして書きなぐっていく
- Tab キー4回 → space で投稿できる

## 懸念
- 会場女子大だが普通に入れる？守衛でooc2020の受付を提示する感じ？（イメージ湧いてない）
- PCでメモできる程度のキャパはある？立ち見はしんどいが
- 12:50 からどっかで時間潰すけどその辺でok？不審者認定されへん？
  - ~~できれば運動したいんですが（シャッフルダンスなんですが（さすがに自重しましょう~~

## todo
- [x] tweet 参加します、メモはこっちで書きます with #ooc_2020
- [x] 参加
- [x] 報告用に整形＆各種タスク配備（ :warning: ここではやらない。ローカルで）
- [x] このメモスタイルの感想をまとめる
- [x] tweet 参加した感想 with #ooc_2020 and このメモスタイルの感想も
- [x] close here

**Comment by stakiran** [comment]
あああ

**Comment by stakiran** [comment]
## コメント方法試してる
- tab x4 → space で投稿後、新しいコメント欄にフォーカスが当たるので、続けて投稿できる。
  - win10+firefoxの場合。macだとどうだろ。

**Comment by stakiran** [comment]
## タイムテーブル見て参加するの設計した


メモ

- ランチタイムセッションはやめる
  - 朝からで先着300名 → https://twitter.com/oocon_2020/status/1225673070032982017
  - だるい

**Comment by stakiran** [comment]
## 明日なので追加情報

### マップ1
![image](https://user-images.githubusercontent.com/23325839/74585154-036d7480-501d-11ea-9de3-e3eb79dc829a.png) from [Googleマップ](https://www.google.com/maps/place/%E3%81%8A%E8%8C%B6%E3%81%AE%E6%B0%B4%E5%A5%B3%E5%AD%90%E5%A4%A7%E5%AD%A6/@35.7186168,139.7318569,17.33z/data=!4m5!3m4!1s0x60188da7f9b14899:0x8be4584bf2f85995!8m2!3d35.71879!4d139.7321363)

### マップ2
![構内マップ](https://user-images.githubusercontent.com/23325839/74585089-598de800-501c-11ea-8510-51d006295740.png) from [oocツイートより](https://twitter.com/oocon_2020/status/1228572438574727169)

### 門
[正門のみ](https://twitter.com/oocon_2020/status/1228520153035337729)

### 受付開始
[10:00から](https://twitter.com/oocon_2020/status/1228519126085197825)

[共通講義棟の1Fでやるみたい](https://twitter.com/nobubump0/status/1228601239178362882)

### コロナだけど
2020/02/15 18:08:44 現時点で中止予定はなし。

**Comment by stakiran** [comment]
## 当日だが参加する？
- 迷っている。やはりコロナが心配。
- [YouTube Live するからリモート参加は可能らしい](https://twitter.com/oocon_2020/status/1228577924053233665)。
- 本音は？
  - 行きたい
  - ~~行かないと会社で怒られる（「OOCお前の役割やろがい」~~ これはどうでもいい
- 心配事
  - コロナ
  - 雨 ★これなかったら行ってたんだけどｗ
  - 会場広い？座ってストレスなくメモ取れるキャパある？
  - 列待ちという大嫌いな現象に見舞われることはないよね？
- 参加者はどうなってる？
  - 現時点で参加 1250 人、欠席 650。2:1 という比率は中々にエグいのではなかろうか
- でもコロナ怖がってたらどこにも行けないんだよなぁ
  - ここで参加して「楽しかった」「なんともなかった」が得られたら「日々の注意だけで大丈夫やん」と安心感も湧く（だからといって未来も安全である保証はないのだが）

**Comment by stakiran** [comment]
## リモートに切り替えます
- コロナ
- 雨
- 遠出
- 人多い（1000人規模は未経験）

↑ 過去日記見返した限りでは、このクアッドコンボを前にストレスフリーであれる気がしなかった。

**Comment by stakiran** [comment]
## connpass キャンセル完了
あとは youtube live を待つのみ。まだ url は無さそうだが、始まる直前くらいに twitter で公開される感じ？

:train: [キャンセル欄のコメント](https://ooc.connpass.com/event/157193/ptype/225976/cancelled/?page=7) が言い訳色々で結構面白い。露骨な「コロナ対策」勢もあれば「体調不調で……」的なテンプレまで

**Comment by stakiran** [comment]
## youtube live url 公開された
https://www.youtube.com/channel/UCzhlHRuKIUdziI-qvwr4SLg

e と d がまだない。

**Comment by stakiran** [comment]
## ハッシュタグリスト
from https://twitter.com/oocon_2020/status/1228850203442081793

```
【ハッシュタグのお知らせ】
各セッションのハッシュタグは以下の通りです。
Hall A #ooc_2020 #ooc_a
Hall B #ooc_2020 #ooc_b
Hall C #ooc_2020 #ooc_c
Hall D #ooc_2020 #ooc_d
Hall E #ooc_2020 #ooc_e
#ooc_2020
```

**Comment by stakiran** [comment]
## 参加どうしよ
リモートなので昼飯とか休憩とか考えずに自分の聴きたいものを選べる。ので再考したい

- 複数 youtube live ……は聖徳太子じゃないし無理
- 11:00 からご飯食べてるのでオープニング見逃しちゃう……
- レベル高いのはいいや ← DDDとかよくわかってないので
- 無理矢理 OOP に結びつけてる宣伝色強いのもいいや
-

**Comment by stakiran** [comment]
## これで
:warning: see https://github.com/stakiran/note/issues/1#issuecomment-586668713

- x1100-1135 共2-201 ooc-a https://www.youtube.com/watch?v=pryXMNLG62A
- x1150-1215 共1-301 ooc-e https://www.youtube.com/watch?v=MnsbUGfUMoA
- x1220-1235 共1-304 ooc-d https://www.youtube.com/watch?v=ZjmgN-__CVE
- x1250-1345 共2-201 ooc-a https://www.youtube.com/watch?v=pryXMNLG62A
- x1400-1445 共2-101 ooc-b 
- 1500-1545 共2-101 ooc-b 
- 1600-1645 共2-101 ooc-b 
- 1700-1730 共2-201 ooc-a 

部屋番号と ooc-X の対応がわからん…… [タイムテーブル](https://fortee.jp/object-oriented-conference-2020/timetable) の並び順で a, b, c, ... で良い？とりあえず a は確定

**Comment by stakiran** [comment]
## 聴講メモはこっちで https://github.com/stakiran/note/issues/2

**Comment by stakiran** [comment]
## アクセスこんな感じです
![image](https://user-images.githubusercontent.com/23325839/74599108-4896b280-50c0-11ea-8606-ae088770e306.png)

**Comment by stakiran** [comment]
:warning: youtube live は仕切り直すたびに新しい url で開催するので https://www.youtube.com/channel/UCzhlHRuKIUdziI-qvwr4SLg こっちから都度新しい動画探すべき（最初の動画上でそのまま更新されるかと思ってハマった）

**Comment by stakiran** [comment]
## アクセスこんな感じ
![image](https://user-images.githubusercontent.com/23325839/74599848-f0fe4400-50cb-11ea-91b8-eaf46b4b273b.png)

ハッシュタグに数日前 1 回、当日 2 回ほど「issue に書いてます」投げて、見に来るのが 3-6 人くらいって感じかしらん？

**Comment by stakiran** [comment]
## このメモスタイルの感想をまとめる
- :o: 自分の場所なので好きなペースで好き勝手に書ける
- :o: 絵文字使えるしコピペでスクショ貼れるので slack 分報みたいに使える
- :x: comment 時に tab キー4回必要
- :x: コメント増えるとレスポンス重くなる（80comment くらいから危ないか？）
- :x: 見に来てくれる人少ないからコメント、いいねなどもらえない
- :question: 自席だと快適だが現地 macbook air だとどうかわからん（ダメかも

**Comment by stakiran** [comment]
## 今回学んだことベスト5
- リファクタリング = 負債と純資産の割合を変える、というたとえ
- 開発で使う visualizer を、関係や構造を可視化するツールとして使う（chartworkのやつ。JIG）
- 定理公理を使って基本型とユーザー型をたとえた説明
- イベントストーミング
- oop は ddd の基盤となるモデリングパラダイム

**Comment by stakiran** [comment]
## 感想
- 概念を扱う（いきなり手を動かす前に概念で言語化する、整理する）ことはやっぱり大切
  - 会社では通じないし軽視されがちだけど、やっぱ大切だよなーと再認識できたので良かった
- リモートでイベント参加してメモする、という初体験。楽しかった（備忘だけで一日過ごせるマンなので
- ハッシュタグで積極的につぶやかせるスタイルで、twitter も賑わっていて、見ていて楽しかった、寂しくなかった
- ippon パネラーレベルの人たち、知識量えぐい（そして年季古い）
  - ずっとそれで遊んでる人と、せいぜい会社で頑張ってひとりで取り組むこともある（僕）程度では、まあ全然違いますわねと
  - （僕は部署内では一番できるけど）まだまだ全然初心者レベルだと再認識できた
- 集中すれば自席リモート参加でも 11-16 くらいで力尽きる（ので現地参加は半日以上だと正直ハードル高いと再認識）

**Comment by stakiran** [comment]
## ありがとうございました
